# add_subdirectory(MEKF)
# add_subdirectory(QIEKF)
# add_subdirectory(Third_Party)
add_subdirectory(lora)
# add_subdirectory(packets)
# add_subdirectory(pico-logger)
add_subdirectory(gps)
add_subdirectory(imus)
add_subdirectory(9axisIMU)
add_subdirectory(mags)
add_subdirectory(baros)
add_subdirectory(actuators)
add_subdirectory(math_utils)
