/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_ROCKETRY_DATA_PB_H_INCLUDED
#define PB_ROCKETRY_DATA_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* GPS Fix type enumeration */
typedef enum _rocketry_GpsFix {
    rocketry_GpsFix_UNKNOWN_GPSFIX = 0, /* Unknown fix type (protobuf treats 0 enums as unset) */
    rocketry_GpsFix_NO_FIX = 1,
    rocketry_GpsFix_DEAD_RECKONING_ONLY = 2,
    rocketry_GpsFix_FIX_2D = 3,
    rocketry_GpsFix_FIX_3D = 4,
    rocketry_GpsFix_GPS_PLUS_DEAD_RECKONING = 5,
    rocketry_GpsFix_TIME_ONLY_FIX = 6
} rocketry_GpsFix;

/* Enum to identify the payload type */
typedef enum _rocketry_TrackerPacket_PacketType {
    rocketry_TrackerPacket_PacketType_UNKNOWN = 0,
    rocketry_TrackerPacket_PacketType_GPS = 1, /* GPS position data */
    rocketry_TrackerPacket_PacketType_ISM_PRIMARY = 2, /* Primary IMU data */
    rocketry_TrackerPacket_PacketType_ISM_SECONDARY = 3, /* Secondary IMU data */
    rocketry_TrackerPacket_PacketType_LSM = 4, /* LSM6DSO32 IMU data */
    rocketry_TrackerPacket_PacketType_ACCEL = 5, /* ADXL accelerometer */
    rocketry_TrackerPacket_PacketType_BARO = 6, /* Barometer */
    rocketry_TrackerPacket_PacketType_USER_LOCATION = 7 /* User's phone location */
} rocketry_TrackerPacket_PacketType;

/* Struct definitions */
/* GPS position data (simplified from MiniData) */
typedef struct _rocketry_GpsData {
    double lat;
    double lon;
    double alt;
    uint32_t num_sats;
    rocketry_GpsFix fix_type;
    uint32_t itow; /* GPS Millisecond Time of Week */
    uint32_t time_accuracy_estimate_ns;
    int32_t nanos; /* Nanoseconds of second, range -1e9 .. 1e9 */
    int32_t year; /* Year, range 1999..2099 */
    int32_t month; /* Month, range 1..12 */
    int32_t day; /* Day of Month, range 1..31 */
    int32_t hour; /* Hour of Day, range 0..23 */
    int32_t min; /* Minute of Hour, range 0..59 */
    int32_t sec; /* Seconds of Minute, range 0..59 */
    int32_t valid;
} rocketry_GpsData;

typedef struct _rocketry_ImuData {
    double accel_x; /* Accelerometer X-axis */
    double accel_y; /* Accelerometer Y-axis */
    double accel_z; /* Accelerometer Z-axis */
    double gyro_x; /* Gyroscope X-axis */
    double gyro_y; /* Gyroscope Y-axis */
    double gyro_z; /* Gyroscope Z-axis */
} rocketry_ImuData;

typedef struct _rocketry_AccelData {
    double accel_x; /* Accelerometer X-axis */
    double accel_y; /* Accelerometer Y-axis */
    double accel_z; /* Accelerometer Z-axis */
} rocketry_AccelData;

typedef struct _rocketry_BaroData {
    double altitude; /* Altitude in meters */
} rocketry_BaroData;

typedef struct _rocketry_UserLocation {
    double lat; /* Latitude in degrees */
    double lon; /* Longitude in degrees */
} rocketry_UserLocation;

/* The unified message format for all tracker data */
typedef struct _rocketry_TrackerPacket {
    /* Common fields for all packet types */
    uint32_t device_id;
    uint32_t msg_num;
    uint64_t time_since_boot;
    rocketry_TrackerPacket_PacketType packet_type;
    pb_size_t which_payload;
    union _rocketry_TrackerPacket_payload {
        rocketry_GpsData gps;
        rocketry_ImuData imu;
        rocketry_AccelData accel;
        rocketry_BaroData baro;
        rocketry_UserLocation user_location;
    } payload;
} rocketry_TrackerPacket;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _rocketry_GpsFix_MIN rocketry_GpsFix_UNKNOWN_GPSFIX
#define _rocketry_GpsFix_MAX rocketry_GpsFix_TIME_ONLY_FIX
#define _rocketry_GpsFix_ARRAYSIZE ((rocketry_GpsFix)(rocketry_GpsFix_TIME_ONLY_FIX+1))

#define _rocketry_TrackerPacket_PacketType_MIN rocketry_TrackerPacket_PacketType_UNKNOWN
#define _rocketry_TrackerPacket_PacketType_MAX rocketry_TrackerPacket_PacketType_USER_LOCATION
#define _rocketry_TrackerPacket_PacketType_ARRAYSIZE ((rocketry_TrackerPacket_PacketType)(rocketry_TrackerPacket_PacketType_USER_LOCATION+1))

#define rocketry_TrackerPacket_packet_type_ENUMTYPE rocketry_TrackerPacket_PacketType

#define rocketry_GpsData_fix_type_ENUMTYPE rocketry_GpsFix






/* Initializer values for message structs */
#define rocketry_TrackerPacket_init_default      {0, 0, 0, _rocketry_TrackerPacket_PacketType_MIN, 0, {rocketry_GpsData_init_default}}
#define rocketry_GpsData_init_default            {0, 0, 0, 0, _rocketry_GpsFix_MIN, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define rocketry_ImuData_init_default            {0, 0, 0, 0, 0, 0}
#define rocketry_AccelData_init_default          {0, 0, 0}
#define rocketry_BaroData_init_default           {0}
#define rocketry_UserLocation_init_default       {0, 0}
#define rocketry_TrackerPacket_init_zero         {0, 0, 0, _rocketry_TrackerPacket_PacketType_MIN, 0, {rocketry_GpsData_init_zero}}
#define rocketry_GpsData_init_zero               {0, 0, 0, 0, _rocketry_GpsFix_MIN, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define rocketry_ImuData_init_zero               {0, 0, 0, 0, 0, 0}
#define rocketry_AccelData_init_zero             {0, 0, 0}
#define rocketry_BaroData_init_zero              {0}
#define rocketry_UserLocation_init_zero          {0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define rocketry_GpsData_lat_tag                 1
#define rocketry_GpsData_lon_tag                 2
#define rocketry_GpsData_alt_tag                 3
#define rocketry_GpsData_num_sats_tag            4
#define rocketry_GpsData_fix_type_tag            5
#define rocketry_GpsData_itow_tag                6
#define rocketry_GpsData_time_accuracy_estimate_ns_tag 7
#define rocketry_GpsData_nanos_tag               8
#define rocketry_GpsData_year_tag                9
#define rocketry_GpsData_month_tag               10
#define rocketry_GpsData_day_tag                 11
#define rocketry_GpsData_hour_tag                12
#define rocketry_GpsData_min_tag                 13
#define rocketry_GpsData_sec_tag                 14
#define rocketry_GpsData_valid_tag               15
#define rocketry_ImuData_accel_x_tag             1
#define rocketry_ImuData_accel_y_tag             2
#define rocketry_ImuData_accel_z_tag             3
#define rocketry_ImuData_gyro_x_tag              4
#define rocketry_ImuData_gyro_y_tag              5
#define rocketry_ImuData_gyro_z_tag              6
#define rocketry_AccelData_accel_x_tag           1
#define rocketry_AccelData_accel_y_tag           2
#define rocketry_AccelData_accel_z_tag           3
#define rocketry_BaroData_altitude_tag           1
#define rocketry_UserLocation_lat_tag            1
#define rocketry_UserLocation_lon_tag            2
#define rocketry_TrackerPacket_device_id_tag     1
#define rocketry_TrackerPacket_msg_num_tag       2
#define rocketry_TrackerPacket_time_since_boot_tag 3
#define rocketry_TrackerPacket_packet_type_tag   4
#define rocketry_TrackerPacket_gps_tag           5
#define rocketry_TrackerPacket_imu_tag           6
#define rocketry_TrackerPacket_accel_tag         7
#define rocketry_TrackerPacket_baro_tag          8
#define rocketry_TrackerPacket_user_location_tag 9

/* Struct field encoding specification for nanopb */
#define rocketry_TrackerPacket_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   device_id,         1) \
X(a, STATIC,   SINGULAR, UINT32,   msg_num,           2) \
X(a, STATIC,   SINGULAR, FIXED64,  time_since_boot,   3) \
X(a, STATIC,   SINGULAR, UENUM,    packet_type,       4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,gps,payload.gps),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,imu,payload.imu),   6) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,accel,payload.accel),   7) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,baro,payload.baro),   8) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,user_location,payload.user_location),   9)
#define rocketry_TrackerPacket_CALLBACK NULL
#define rocketry_TrackerPacket_DEFAULT NULL
#define rocketry_TrackerPacket_payload_gps_MSGTYPE rocketry_GpsData
#define rocketry_TrackerPacket_payload_imu_MSGTYPE rocketry_ImuData
#define rocketry_TrackerPacket_payload_accel_MSGTYPE rocketry_AccelData
#define rocketry_TrackerPacket_payload_baro_MSGTYPE rocketry_BaroData
#define rocketry_TrackerPacket_payload_user_location_MSGTYPE rocketry_UserLocation

#define rocketry_GpsData_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, DOUBLE,   lat,               1) \
X(a, STATIC,   SINGULAR, DOUBLE,   lon,               2) \
X(a, STATIC,   SINGULAR, DOUBLE,   alt,               3) \
X(a, STATIC,   SINGULAR, UINT32,   num_sats,          4) \
X(a, STATIC,   SINGULAR, UENUM,    fix_type,          5) \
X(a, STATIC,   SINGULAR, UINT32,   itow,              6) \
X(a, STATIC,   SINGULAR, UINT32,   time_accuracy_estimate_ns,   7) \
X(a, STATIC,   SINGULAR, INT32,    nanos,             8) \
X(a, STATIC,   SINGULAR, INT32,    year,              9) \
X(a, STATIC,   SINGULAR, INT32,    month,            10) \
X(a, STATIC,   SINGULAR, INT32,    day,              11) \
X(a, STATIC,   SINGULAR, INT32,    hour,             12) \
X(a, STATIC,   SINGULAR, INT32,    min,              13) \
X(a, STATIC,   SINGULAR, INT32,    sec,              14) \
X(a, STATIC,   SINGULAR, INT32,    valid,            15)
#define rocketry_GpsData_CALLBACK NULL
#define rocketry_GpsData_DEFAULT NULL

#define rocketry_ImuData_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, DOUBLE,   accel_x,           1) \
X(a, STATIC,   SINGULAR, DOUBLE,   accel_y,           2) \
X(a, STATIC,   SINGULAR, DOUBLE,   accel_z,           3) \
X(a, STATIC,   SINGULAR, DOUBLE,   gyro_x,            4) \
X(a, STATIC,   SINGULAR, DOUBLE,   gyro_y,            5) \
X(a, STATIC,   SINGULAR, DOUBLE,   gyro_z,            6)
#define rocketry_ImuData_CALLBACK NULL
#define rocketry_ImuData_DEFAULT NULL

#define rocketry_AccelData_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, DOUBLE,   accel_x,           1) \
X(a, STATIC,   SINGULAR, DOUBLE,   accel_y,           2) \
X(a, STATIC,   SINGULAR, DOUBLE,   accel_z,           3)
#define rocketry_AccelData_CALLBACK NULL
#define rocketry_AccelData_DEFAULT NULL

#define rocketry_BaroData_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, DOUBLE,   altitude,          1)
#define rocketry_BaroData_CALLBACK NULL
#define rocketry_BaroData_DEFAULT NULL

#define rocketry_UserLocation_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, DOUBLE,   lat,               1) \
X(a, STATIC,   SINGULAR, DOUBLE,   lon,               2)
#define rocketry_UserLocation_CALLBACK NULL
#define rocketry_UserLocation_DEFAULT NULL

extern const pb_msgdesc_t rocketry_TrackerPacket_msg;
extern const pb_msgdesc_t rocketry_GpsData_msg;
extern const pb_msgdesc_t rocketry_ImuData_msg;
extern const pb_msgdesc_t rocketry_AccelData_msg;
extern const pb_msgdesc_t rocketry_BaroData_msg;
extern const pb_msgdesc_t rocketry_UserLocation_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define rocketry_TrackerPacket_fields &rocketry_TrackerPacket_msg
#define rocketry_GpsData_fields &rocketry_GpsData_msg
#define rocketry_ImuData_fields &rocketry_ImuData_msg
#define rocketry_AccelData_fields &rocketry_AccelData_msg
#define rocketry_BaroData_fields &rocketry_BaroData_msg
#define rocketry_UserLocation_fields &rocketry_UserLocation_msg

/* Maximum encoded size of messages (where known) */
#define ROCKETRY_DATA_PB_H_MAX_SIZE              rocketry_TrackerPacket_size
#define rocketry_AccelData_size                  27
#define rocketry_BaroData_size                   9
#define rocketry_GpsData_size                    135
#define rocketry_ImuData_size                    54
#define rocketry_TrackerPacket_size              161
#define rocketry_UserLocation_size               18

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
