/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "data.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(rocketry_TrackerPacket, rocketry_TrackerPacket, AUTO)


PB_BIND(rocketry_GpsData, rocketry_GpsData, AUTO)


PB_BIND(rocketry_ImuData, rocketry_ImuData, AUTO)


PB_BIND(rocketry_AccelData, rocketry_AccelData, AUTO)


PB_BIND(rocketry_BaroData, rocketry_BaroData, AUTO)


PB_BIND(rocketry_UserLocation, rocketry_UserLocation, AUTO)







#ifndef PB_CONVERT_DOUBLE_FLOAT
/* On some platforms (such as AVR), double is really float.
 * To be able to encode/decode double on these platforms, you need.
 * to define PB_CONVERT_DOUBLE_FLOAT in pb.h or compiler command line.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)
#endif

