/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "SIGMA2_Proto.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(sigma2_CameraCommand, sigma2_CameraCommand, AUTO)


PB_BIND(sigma2_CameraConfig, sigma2_CameraConfig, AUTO)


PB_BIND(sigma2_CommandAck, sigma2_CommandAck, AUTO)


PB_BIND(sigma2_GpsData, sigma2_GpsData, AUTO)


PB_BIND(sigma2_ImuData, sigma2_ImuData, AUTO)


PB_BIND(sigma2_BaroData, sigma2_BaroData, AUTO)


PB_BIND(sigma2_FlightStatus, sigma2_FlightStatus, AUTO)


PB_BIND(sigma2_Health, sigma2_Health, AUTO)


PB_BIND(sigma2_Envelope, sigma2_Envelope, AUTO)











#ifndef PB_CONVERT_DOUBLE_FLOAT
/* On some platforms (such as AVR), double is really float.
 * To be able to encode/decode double on these platforms, you need.
 * to define PB_CONVERT_DOUBLE_FLOAT in pb.h or compiler command line.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)
#endif

