/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_SIGMA2_SIGMA2_PROTO_PB_H_INCLUDED
#define PB_SIGMA2_SIGMA2_PROTO_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* Logical node identity. Mirrors SIGMA2::NodeID in SIGMA2.hpp. 0 = unknown for
 a source, broadcast for a destination. */
typedef enum _sigma2_NodeId {
    sigma2_NodeId_NODE_UNDEFINED = 0,
    sigma2_NodeId_NODE_NOSE_CONE = 1,
    sigma2_NodeId_NODE_PAYLOAD = 2,
    sigma2_NodeId_NODE_EBAY = 3,
    sigma2_NodeId_NODE_ADS = 4,
    sigma2_NodeId_NODE_ANTENNA_TRACKER = 5,
    sigma2_NodeId_NODE_STATIONARY_GS = 6,
    sigma2_NodeId_NODE_MOBILE_NODE1 = 7,
    sigma2_NodeId_NODE_MOBILE_NODE2 = 8,
    sigma2_NodeId_NODE_MOBILE_NODE3 = 9,
    sigma2_NodeId_NODE_MOBILE_NODE4 = 10,
    sigma2_NodeId_NODE_ROCKET_CAM = 11 /* rocket-cam Pico W flight camera controller */
} sigma2_NodeId;

/* Flight state. Superset of pins.hpp::state_t (rocket-cam) and the SIGMA2.hpp
 FLIGHT_STATE enum. */
typedef enum _sigma2_FlightState {
    sigma2_FlightState_FS_UNKNOWN = 0,
    sigma2_FlightState_FS_PAD = 1,
    sigma2_FlightState_FS_BOOST = 2,
    sigma2_FlightState_FS_COAST = 3,
    sigma2_FlightState_FS_APOGEE = 4,
    sigma2_FlightState_FS_RECOVERY = 5,
    sigma2_FlightState_FS_LANDED = 6
} sigma2_FlightState;

/* RushFPV 3.3 GHz band. Values match pins.hpp::VtxBand. */
typedef enum _sigma2_VtxBand {
    sigma2_VtxBand_VTX_BAND_A = 0, /* 3G3 BAND A: 3330-3470 MHz */
    sigma2_VtxBand_VTX_BAND_B = 1 /* 3G3 BAND B: 3170-3310 MHz */
} sigma2_VtxBand;

/* VTX power level. Order and values match pins.hpp::VtxPower so the firmware can
 cast directly to VtxPower and resolve with vtx_power_mw(). */
typedef enum _sigma2_VtxPowerLevel {
    sigma2_VtxPowerLevel_VTX_PIT = 0, /* ~0 mW (pit mode / RF off) */
    sigma2_VtxPowerLevel_VTX_25MW = 1, /* 25 mW */
    sigma2_VtxPowerLevel_VTX_200MW = 2, /* 200 mW */
    sigma2_VtxPowerLevel_VTX_1000MW = 3, /* 1000 mW */
    sigma2_VtxPowerLevel_VTX_4000MW = 4 /* 4000 mW (max) */
} sigma2_VtxPowerLevel;

/* Struct definitions */
/* Phone -> camera. Every field is `optional` so the device applies only the
 fields the sender actually set (proto3 optional => nanopb has_ flags). If both
 band/channel and freq_mhz are present, freq_mhz wins. */
typedef struct _sigma2_CameraCommand {
    bool has_band;
    sigma2_VtxBand band; /* band for band+channel selection */
    bool has_channel;
    uint32_t channel; /* channel 1..8 (1-based, like the console) */
    bool has_freq_mhz;
    uint32_t freq_mhz; /* explicit frequency override in MHz */
    bool has_power;
    sigma2_VtxPowerLevel power; /* VTX power level */
    bool has_rf_enabled;
    bool rf_enabled; /* true = RF on, false = pit mode */
    bool has_camera_record;
    bool camera_record; /* true = start recording, false = stop */
    bool has_request_status;
    bool request_status; /* ask the device to emit a CameraConfig */
} sigma2_CameraCommand;

/* Camera -> phone. Current device configuration / status snapshot. */
typedef struct _sigma2_CameraConfig {
    sigma2_VtxBand band;
    uint32_t channel; /* 1..8, 0 if frequency is not on a known channel */
    uint32_t freq_mhz;
    sigma2_VtxPowerLevel power; /* configured power level */
    uint32_t actual_power_mw; /* measured output power (from VTX 'v' response) */
    bool rf_enabled; /* false = pit mode */
    bool camera_recording;
    sigma2_FlightState flight_state;
    float altitude_agl_m;
    bool vtx_responsive; /* last VTX query returned a valid response */
} sigma2_CameraConfig;

/* Acknowledgement for a received command (folded into the STATUS notify path). */
typedef struct _sigma2_CommandAck {
    uint32_t seq;
    bool ok;
    char message[32];
} sigma2_CommandAck;

typedef struct _sigma2_GpsData {
    double lat;
    double lon;
    double alt_m;
    uint32_t num_sats;
    uint32_t fix_type;
} sigma2_GpsData;

typedef struct _sigma2_ImuData {
    float accel_x;
    float accel_y;
    float accel_z;
    float gyro_x;
    float gyro_y;
    float gyro_z;
} sigma2_ImuData;

typedef struct _sigma2_BaroData {
    float pressure_pa;
    float temperature_c;
    float altitude_m;
} sigma2_BaroData;

typedef struct _sigma2_FlightStatus {
    sigma2_FlightState state;
    float altitude_agl_m;
    float climb_ms;
} sigma2_FlightStatus;

typedef struct _sigma2_Health {
    float battery_v;
    float temperature_c;
    uint32_t error_flags;
    uint32_t uptime_s;
} sigma2_Health;

typedef struct _sigma2_Envelope {
    sigma2_NodeId node_src;
    sigma2_NodeId node_dst;
    uint32_t seq; /* per-sender sequence number, wraps at 2^32 */
    uint64_t timestamp_ms; /* sender time since boot in milliseconds */
    pb_size_t which_payload;
    union {
        /* Camera / VTX control */
        sigma2_CameraCommand cam_command;
        sigma2_CameraConfig cam_config;
        sigma2_CommandAck ack;
        /* Telemetry (skeleton) */
        sigma2_GpsData gps;
        sigma2_ImuData imu;
        sigma2_BaroData baro;
        sigma2_FlightStatus flight;
        sigma2_Health health;
    } payload;
} sigma2_Envelope;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _sigma2_NodeId_MIN sigma2_NodeId_NODE_UNDEFINED
#define _sigma2_NodeId_MAX sigma2_NodeId_NODE_ROCKET_CAM
#define _sigma2_NodeId_ARRAYSIZE ((sigma2_NodeId)(sigma2_NodeId_NODE_ROCKET_CAM+1))

#define _sigma2_FlightState_MIN sigma2_FlightState_FS_UNKNOWN
#define _sigma2_FlightState_MAX sigma2_FlightState_FS_LANDED
#define _sigma2_FlightState_ARRAYSIZE ((sigma2_FlightState)(sigma2_FlightState_FS_LANDED+1))

#define _sigma2_VtxBand_MIN sigma2_VtxBand_VTX_BAND_A
#define _sigma2_VtxBand_MAX sigma2_VtxBand_VTX_BAND_B
#define _sigma2_VtxBand_ARRAYSIZE ((sigma2_VtxBand)(sigma2_VtxBand_VTX_BAND_B+1))

#define _sigma2_VtxPowerLevel_MIN sigma2_VtxPowerLevel_VTX_PIT
#define _sigma2_VtxPowerLevel_MAX sigma2_VtxPowerLevel_VTX_4000MW
#define _sigma2_VtxPowerLevel_ARRAYSIZE ((sigma2_VtxPowerLevel)(sigma2_VtxPowerLevel_VTX_4000MW+1))

#define sigma2_CameraCommand_band_ENUMTYPE sigma2_VtxBand
#define sigma2_CameraCommand_power_ENUMTYPE sigma2_VtxPowerLevel

#define sigma2_CameraConfig_band_ENUMTYPE sigma2_VtxBand
#define sigma2_CameraConfig_power_ENUMTYPE sigma2_VtxPowerLevel
#define sigma2_CameraConfig_flight_state_ENUMTYPE sigma2_FlightState





#define sigma2_FlightStatus_state_ENUMTYPE sigma2_FlightState


#define sigma2_Envelope_node_src_ENUMTYPE sigma2_NodeId
#define sigma2_Envelope_node_dst_ENUMTYPE sigma2_NodeId


/* Initializer values for message structs */
#define sigma2_CameraCommand_init_default        {false, _sigma2_VtxBand_MIN, false, 0, false, 0, false, _sigma2_VtxPowerLevel_MIN, false, 0, false, 0, false, 0}
#define sigma2_CameraConfig_init_default         {_sigma2_VtxBand_MIN, 0, 0, _sigma2_VtxPowerLevel_MIN, 0, 0, 0, _sigma2_FlightState_MIN, 0, 0}
#define sigma2_CommandAck_init_default           {0, 0, ""}
#define sigma2_GpsData_init_default              {0, 0, 0, 0, 0}
#define sigma2_ImuData_init_default              {0, 0, 0, 0, 0, 0}
#define sigma2_BaroData_init_default             {0, 0, 0}
#define sigma2_FlightStatus_init_default         {_sigma2_FlightState_MIN, 0, 0}
#define sigma2_Health_init_default               {0, 0, 0, 0}
#define sigma2_Envelope_init_default             {_sigma2_NodeId_MIN, _sigma2_NodeId_MIN, 0, 0, 0, {sigma2_CameraCommand_init_default}}
#define sigma2_CameraCommand_init_zero           {false, _sigma2_VtxBand_MIN, false, 0, false, 0, false, _sigma2_VtxPowerLevel_MIN, false, 0, false, 0, false, 0}
#define sigma2_CameraConfig_init_zero            {_sigma2_VtxBand_MIN, 0, 0, _sigma2_VtxPowerLevel_MIN, 0, 0, 0, _sigma2_FlightState_MIN, 0, 0}
#define sigma2_CommandAck_init_zero              {0, 0, ""}
#define sigma2_GpsData_init_zero                 {0, 0, 0, 0, 0}
#define sigma2_ImuData_init_zero                 {0, 0, 0, 0, 0, 0}
#define sigma2_BaroData_init_zero                {0, 0, 0}
#define sigma2_FlightStatus_init_zero            {_sigma2_FlightState_MIN, 0, 0}
#define sigma2_Health_init_zero                  {0, 0, 0, 0}
#define sigma2_Envelope_init_zero                {_sigma2_NodeId_MIN, _sigma2_NodeId_MIN, 0, 0, 0, {sigma2_CameraCommand_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define sigma2_CameraCommand_band_tag            1
#define sigma2_CameraCommand_channel_tag         2
#define sigma2_CameraCommand_freq_mhz_tag        3
#define sigma2_CameraCommand_power_tag           4
#define sigma2_CameraCommand_rf_enabled_tag      5
#define sigma2_CameraCommand_camera_record_tag   6
#define sigma2_CameraCommand_request_status_tag  7
#define sigma2_CameraConfig_band_tag             1
#define sigma2_CameraConfig_channel_tag          2
#define sigma2_CameraConfig_freq_mhz_tag         3
#define sigma2_CameraConfig_power_tag            4
#define sigma2_CameraConfig_actual_power_mw_tag  5
#define sigma2_CameraConfig_rf_enabled_tag       6
#define sigma2_CameraConfig_camera_recording_tag 7
#define sigma2_CameraConfig_flight_state_tag     8
#define sigma2_CameraConfig_altitude_agl_m_tag   9
#define sigma2_CameraConfig_vtx_responsive_tag   10
#define sigma2_CommandAck_seq_tag                1
#define sigma2_CommandAck_ok_tag                 2
#define sigma2_CommandAck_message_tag            3
#define sigma2_GpsData_lat_tag                   1
#define sigma2_GpsData_lon_tag                   2
#define sigma2_GpsData_alt_m_tag                 3
#define sigma2_GpsData_num_sats_tag              4
#define sigma2_GpsData_fix_type_tag              5
#define sigma2_ImuData_accel_x_tag               1
#define sigma2_ImuData_accel_y_tag               2
#define sigma2_ImuData_accel_z_tag               3
#define sigma2_ImuData_gyro_x_tag                4
#define sigma2_ImuData_gyro_y_tag                5
#define sigma2_ImuData_gyro_z_tag                6
#define sigma2_BaroData_pressure_pa_tag          1
#define sigma2_BaroData_temperature_c_tag        2
#define sigma2_BaroData_altitude_m_tag           3
#define sigma2_FlightStatus_state_tag            1
#define sigma2_FlightStatus_altitude_agl_m_tag   2
#define sigma2_FlightStatus_climb_ms_tag         3
#define sigma2_Health_battery_v_tag              1
#define sigma2_Health_temperature_c_tag          2
#define sigma2_Health_error_flags_tag            3
#define sigma2_Health_uptime_s_tag               4
#define sigma2_Envelope_node_src_tag             1
#define sigma2_Envelope_node_dst_tag             2
#define sigma2_Envelope_seq_tag                  3
#define sigma2_Envelope_timestamp_ms_tag         4
#define sigma2_Envelope_cam_command_tag          10
#define sigma2_Envelope_cam_config_tag           11
#define sigma2_Envelope_ack_tag                  12
#define sigma2_Envelope_gps_tag                  20
#define sigma2_Envelope_imu_tag                  21
#define sigma2_Envelope_baro_tag                 22
#define sigma2_Envelope_flight_tag               23
#define sigma2_Envelope_health_tag               24

/* Struct field encoding specification for nanopb */
#define sigma2_CameraCommand_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UENUM,    band,              1) \
X(a, STATIC,   OPTIONAL, UINT32,   channel,           2) \
X(a, STATIC,   OPTIONAL, UINT32,   freq_mhz,          3) \
X(a, STATIC,   OPTIONAL, UENUM,    power,             4) \
X(a, STATIC,   OPTIONAL, BOOL,     rf_enabled,        5) \
X(a, STATIC,   OPTIONAL, BOOL,     camera_record,     6) \
X(a, STATIC,   OPTIONAL, BOOL,     request_status,    7)
#define sigma2_CameraCommand_CALLBACK NULL
#define sigma2_CameraCommand_DEFAULT NULL

#define sigma2_CameraConfig_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    band,              1) \
X(a, STATIC,   SINGULAR, UINT32,   channel,           2) \
X(a, STATIC,   SINGULAR, UINT32,   freq_mhz,          3) \
X(a, STATIC,   SINGULAR, UENUM,    power,             4) \
X(a, STATIC,   SINGULAR, UINT32,   actual_power_mw,   5) \
X(a, STATIC,   SINGULAR, BOOL,     rf_enabled,        6) \
X(a, STATIC,   SINGULAR, BOOL,     camera_recording,   7) \
X(a, STATIC,   SINGULAR, UENUM,    flight_state,      8) \
X(a, STATIC,   SINGULAR, FLOAT,    altitude_agl_m,    9) \
X(a, STATIC,   SINGULAR, BOOL,     vtx_responsive,   10)
#define sigma2_CameraConfig_CALLBACK NULL
#define sigma2_CameraConfig_DEFAULT NULL

#define sigma2_CommandAck_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   seq,               1) \
X(a, STATIC,   SINGULAR, BOOL,     ok,                2) \
X(a, STATIC,   SINGULAR, STRING,   message,           3)
#define sigma2_CommandAck_CALLBACK NULL
#define sigma2_CommandAck_DEFAULT NULL

#define sigma2_GpsData_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, DOUBLE,   lat,               1) \
X(a, STATIC,   SINGULAR, DOUBLE,   lon,               2) \
X(a, STATIC,   SINGULAR, DOUBLE,   alt_m,             3) \
X(a, STATIC,   SINGULAR, UINT32,   num_sats,          4) \
X(a, STATIC,   SINGULAR, UINT32,   fix_type,          5)
#define sigma2_GpsData_CALLBACK NULL
#define sigma2_GpsData_DEFAULT NULL

#define sigma2_ImuData_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    accel_x,           1) \
X(a, STATIC,   SINGULAR, FLOAT,    accel_y,           2) \
X(a, STATIC,   SINGULAR, FLOAT,    accel_z,           3) \
X(a, STATIC,   SINGULAR, FLOAT,    gyro_x,            4) \
X(a, STATIC,   SINGULAR, FLOAT,    gyro_y,            5) \
X(a, STATIC,   SINGULAR, FLOAT,    gyro_z,            6)
#define sigma2_ImuData_CALLBACK NULL
#define sigma2_ImuData_DEFAULT NULL

#define sigma2_BaroData_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    pressure_pa,       1) \
X(a, STATIC,   SINGULAR, FLOAT,    temperature_c,     2) \
X(a, STATIC,   SINGULAR, FLOAT,    altitude_m,        3)
#define sigma2_BaroData_CALLBACK NULL
#define sigma2_BaroData_DEFAULT NULL

#define sigma2_FlightStatus_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    state,             1) \
X(a, STATIC,   SINGULAR, FLOAT,    altitude_agl_m,    2) \
X(a, STATIC,   SINGULAR, FLOAT,    climb_ms,          3)
#define sigma2_FlightStatus_CALLBACK NULL
#define sigma2_FlightStatus_DEFAULT NULL

#define sigma2_Health_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    battery_v,         1) \
X(a, STATIC,   SINGULAR, FLOAT,    temperature_c,     2) \
X(a, STATIC,   SINGULAR, UINT32,   error_flags,       3) \
X(a, STATIC,   SINGULAR, UINT32,   uptime_s,          4)
#define sigma2_Health_CALLBACK NULL
#define sigma2_Health_DEFAULT NULL

#define sigma2_Envelope_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    node_src,          1) \
X(a, STATIC,   SINGULAR, UENUM,    node_dst,          2) \
X(a, STATIC,   SINGULAR, UINT32,   seq,               3) \
X(a, STATIC,   SINGULAR, UINT64,   timestamp_ms,      4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,cam_command,payload.cam_command),  10) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,cam_config,payload.cam_config),  11) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,ack,payload.ack),  12) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,gps,payload.gps),  20) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,imu,payload.imu),  21) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,baro,payload.baro),  22) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,flight,payload.flight),  23) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,health,payload.health),  24)
#define sigma2_Envelope_CALLBACK NULL
#define sigma2_Envelope_DEFAULT NULL
#define sigma2_Envelope_payload_cam_command_MSGTYPE sigma2_CameraCommand
#define sigma2_Envelope_payload_cam_config_MSGTYPE sigma2_CameraConfig
#define sigma2_Envelope_payload_ack_MSGTYPE sigma2_CommandAck
#define sigma2_Envelope_payload_gps_MSGTYPE sigma2_GpsData
#define sigma2_Envelope_payload_imu_MSGTYPE sigma2_ImuData
#define sigma2_Envelope_payload_baro_MSGTYPE sigma2_BaroData
#define sigma2_Envelope_payload_flight_MSGTYPE sigma2_FlightStatus
#define sigma2_Envelope_payload_health_MSGTYPE sigma2_Health

extern const pb_msgdesc_t sigma2_CameraCommand_msg;
extern const pb_msgdesc_t sigma2_CameraConfig_msg;
extern const pb_msgdesc_t sigma2_CommandAck_msg;
extern const pb_msgdesc_t sigma2_GpsData_msg;
extern const pb_msgdesc_t sigma2_ImuData_msg;
extern const pb_msgdesc_t sigma2_BaroData_msg;
extern const pb_msgdesc_t sigma2_FlightStatus_msg;
extern const pb_msgdesc_t sigma2_Health_msg;
extern const pb_msgdesc_t sigma2_Envelope_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define sigma2_CameraCommand_fields &sigma2_CameraCommand_msg
#define sigma2_CameraConfig_fields &sigma2_CameraConfig_msg
#define sigma2_CommandAck_fields &sigma2_CommandAck_msg
#define sigma2_GpsData_fields &sigma2_GpsData_msg
#define sigma2_ImuData_fields &sigma2_ImuData_msg
#define sigma2_BaroData_fields &sigma2_BaroData_msg
#define sigma2_FlightStatus_fields &sigma2_FlightStatus_msg
#define sigma2_Health_fields &sigma2_Health_msg
#define sigma2_Envelope_fields &sigma2_Envelope_msg

/* Maximum encoded size of messages (where known) */
#define SIGMA2_SIGMA2_PROTO_PB_H_MAX_SIZE        sigma2_Envelope_size
#define sigma2_BaroData_size                     15
#define sigma2_CameraCommand_size                22
#define sigma2_CameraConfig_size                 35
#define sigma2_CommandAck_size                   41
#define sigma2_Envelope_size                     64
#define sigma2_FlightStatus_size                 12
#define sigma2_GpsData_size                      39
#define sigma2_Health_size                       22
#define sigma2_ImuData_size                      30

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
